project:
  type: website

website:
  title: "AlexWeinreb"
  site-url: https://alexweinreb.github.io
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/AlexWeinreb
      - icon: mastodon
        href: https://genomic.social/@AlexWe
format:
  html:
    theme: cosmo
    css: styles.css



